from github import Github, GithubException
from state import AgentState
import os
import uuid

from utils.commit import _commit_file_changes

from utils.parser import _extract_file_blocks


def pr_opener_agent(state: AgentState) -> AgentState:
    """
    Agent 5: Creates a new branch and opens a real GitHub Pull Request.
    """
    print("\n[Agent 5 - PR Opener] Opening pull request...")

    try:
        g = Github(os.getenv("GITHUB_TOKEN"))
        repo = g.get_repo(state["repo_full_name"])

        base_branch = repo.default_branch
        main_branch = repo.get_branch(base_branch)
        base_name = f"fix/issue-auto-{state['issue_title'][:30].lower().replace(' ', '-').replace('/', '-')}"
        base_name = "".join(c for c in base_name if c.isalnum() or c in "-/")
        base_name = base_name.strip("-/")

        branch_name = f"{base_name}-{uuid.uuid4().hex[:8]}"
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha
            )
            print(f"  ✓ Created branch: {branch_name}")
        except GithubException as e:
            print(f"  ✗ Failed to create branch: {e}")
            raise

        patch_blocks = _extract_file_blocks(state.get("patch", ""))
        test_blocks = _extract_file_blocks(state.get("tests", ""))
        all_blocks = patch_blocks + test_blocks

        if not all_blocks:
            raise ValueError(
                "Generated fix did not include any file blocks, so no commit could be created."
            )

        _commit_file_changes(
            repo=repo,
            branch_name=branch_name,
            file_blocks=all_blocks,
            commit_prefix=f"fix: {state['issue_title'][:40]}",
        )

        print(f"  ✓ Committed {len(all_blocks)} file change(s) to {branch_name}")

        # Build PR body
        pr_body = f"""## 🤖 Automated Fix

This PR was generated by a multi-agent AI system in response to the issue.

### Issue
{state["issue_title"]}

### Fix Plan
{state["fix_plan"]}

### Changes
{state["patch"]}

### Tests Added
```python
{state["tests"]}
```

---
*Generated by [github-agent](https://github.com/{state["repo_full_name"]})*
"""

        # Open the pull request
        comparison = repo.compare(base=base_branch, head=branch_name)
        if comparison.ahead_by == 0:
            raise ValueError(
                f"Branch {branch_name} has no commits ahead of main after applying the generated fix."
            )

        pr = repo.create_pull(
            title=f"fix: {state['issue_title']}",
            body=pr_body,
            head=branch_name,
            base=base_branch,
        )

        print(f"  ✓ PR opened: {pr.html_url}")
        return {**state, "pr_url": pr.html_url}

    except Exception as e:
        print(f"  ✗ PR Opener failed: {e}")
        return {**state, "error": f"PR Opener failed: {str(e)}"}
